name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
    secrets:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
