name: CI

on:
  push:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml
    secrets:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

  debug:
    uses: ./.github/workflows/debug.yml
    secrets:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
