name: Publish

on:
  workflow_call:

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all history so that we can determine the version to release.
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
          registry-url: https://registry.npmjs.org
          scope: '@morpho-org'

      # Required to use OIDC trusted publishing.
      - run: npm install -g npm@latest

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build

      - name: Publish to npm
        run: pnpm publish --no-git-checks --access public

